library(readxl)
library(dplyr)

Data <- read_excel("C:/Users/KPVog/OneDrive/Documents/ER visit risks for Shiny App.xlsx")
ER2019_age <- Data %>%  filter(Year == 2019, Characteristics == "Patient Age Group")  
ER2019_age1 <- ER2019_age %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2019_Income <- Data %>% filter(Year == 2019, Characteristics == "Patient Community-level Income")
ER2019_income1 <- ER2019_Income %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2019_race <- Data %>% filter(Year == 2019, Characteristics == "Patient Race/Ethnicity")
ER2019_race1 <- ER2019_race %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2020_age <- Data %>%  filter(Year == 2020, Characteristics == "Patient Age Group")  
ER2020_age1 <- ER2020_age %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2020_Income <- Data %>% filter(Year == 2020, Characteristics == "Patient Community-level Income")
ER2020_income1 <- ER2020_Income %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2020_race <- Data %>% filter(Year == 2020, Characteristics == "Patient Race/Ethnicity")
ER2020_race1 <- ER2020_race %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2021_age <- Data %>% filter(Year == 2021, Characteristics == "Patient Age Group")  
ER2021_age1 <- ER2020_age %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2021_Income <- Data %>% filter(Year == 2021, Characteristics == "Patient Community-level Income")
ER2021_income1 <- ER2021_Income %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
ER2021_race <- Data %>% filter(Year == 2021, Characteristics == "Patient Race/Ethnicity")
ER2021_race1 <- ER2021_race %>% select(-"Type of ED Visit", -Outcome, -"Measure Names")
